project:
  type: website
  output-dir: docs

website:
  title: "llm-assisted-text-analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - "LLM-Assisted Analysis of Car Reviews.qmd"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



